refactor stuff, add makefile and systemd unit, stop relying on tmux

diff --git a/vm/scripts/attach b/vm/scripts/attach
--- a/vm/scripts/attach
+++ b/vm/scripts/attach
@@ -3,6 +3,20 @@ set -e
 
 rootdir=/etc/vm
 name="$1"
+
 . "$rootdir/utils.sh"
 
-tmux attach -t vm-"$name"
+sockfile="$(consolefile "$name")"
+if ! test -S "$sockfile"; then
+    echo "error: $name is not running" >&2
+    exit 1
+fi
+
+if command -v minicom >/dev/null; then
+    exec minicom -D "unix#$sockfile"
+elif command -v socat >/dev/null; then
+    exec socat -,rawer,escape=0x1d "unix-connect:$sockfile"
+else
+    echo "error: need minicom or socat to attach to VM console" >&2
+    exit 2
+fi
diff --git a/vm/scripts/start b/vm/scripts/start
--- a/vm/scripts/start
+++ b/vm/scripts/start
@@ -3,4 +3,14 @@
 name="$1"
 rootdir=/etc/vm
 
-tmux new-session -ds vm-"$name" "exec $rootdir/scripts/launch $1"
+. "$rootdir"/utils.sh
+
+pid=$(getpid "$name")
+if test -n "$pid"; then
+    echo "error: $name is already running" >&2
+    exit 1
+fi
+
+mkdir -p /run/vm/"$name"
+"$rootdir/scripts/launch" "$name" &
+echo $! > /run/vm/"$name"/pid
diff --git a/vm/scripts/stop b/vm/scripts/stop
--- a/vm/scripts/stop
+++ b/vm/scripts/stop
@@ -2,6 +2,13 @@
 set -e
 
 name="$1"
+rootdir=/etc/vm
 
-tmux kill-session -t vm-"$name"
-ip link del vm-"$name"
+. "$rootdir"/utils.sh
+
+pid=$(getpid "$name")
+if test -z "$pid"; then
+    echo "error: $name is not running" >&2
+    exit 1
+fi
+kill "$pid"
